### ISSUE TITLE
react-native-cfddlc <> cfd-dlc-js mismatch

### ISSUE THREAD

**Issue by satirn** [atomicfinance/react-native-cfddlc#1]
I can't seem to get the current master branch of react-native-cfddlc to play nice with the cfd-dlc-js submodule. 

From the latest commit on this repo, my understanding is that the [bump-cfd-dlc-to-fix-default-vout-serial-id](https://github.com/AtomicFinance/cfd-dlc-js/tree/bump-cfd-dlc-to-fix-default-vout-serial-id) branch (commit [ee255b5](https://github.com/AtomicFinance/cfd-dlc-js/commit/ee255b5ff1dcf4d32ded8469dc89a47873d9f277)) should be compatible with this master branch. However, when attempting to use this package in a test app, I'm getting illegal argument errors using the request structure suggested by the types for e.g. the `CreateCetAdaptorSignatures` cdf-dlc-js method:
```
{"error": {"code": 1, "message": "hex to byte convert error.", "type": "illegal_argument"}}
```
and similarly with the `GetRawRefundTxSignature` method.

The interface I'm using here (provided by this lib) for `CreateCetAdaptorSignatures` is
```
export interface CreateCetAdaptorSignaturesRequest {
    cetsHex: string[];
    privkey: string;
    fundTxId: string;
    fundVout?: number;
    localFundPubkey: string;
    remoteFundPubkey: string;
    oraclePubkey: string;
    oracleRValues: string[];
    fundInputAmount: bigint | number;
    messagesList: Messages[];
}
```
And that expected by the same function in the ee255b5 commit (of cfd-dlc-js) is of the form:
```
{
  cets: string[],
  privkey: string,
  oraclePubkey: string,
  oracleRValues: string[],
  messages: string[][],
  fundTxId: string,
  fundVout: number,
  fundInputAmount: number,
  localFundPubkey: string,
  remoteFundPubkey: string
}
```

So theres a clear discrepancy between the `messages`/`messagesList` and `cets`/`cetsHex` argument/types, as well as more minor discrepancies for `fundVout` and `fundInputAmount`.

I have tried to remediate the interface mismatch (so far unsuccessfully) but before I go any further, please can you confirm which `react-native-cfddlc`/`cfd-dlc-js` are expected to be compatible and/or which branches/tags you're currently working with. Thanks

**Comment by satirn** [comment]
Spotted that the corresponding wrapper function looks like this:

```
export function CreateCetAdaptorSignatures(
  cets: string[],
  privkey: string,
  oraclePubkey: string,
  oracleRValues: string[],
  messages: string[][],
  fundTxId: string,
  fundVout: number,
  fundInputAmount: number,
  localFundPubkey: string,
  remoteFundPubkey: string
) {
  const req: cfddlcjs.CreateCetAdaptorSignaturesRequest = {
    cetsHex: cets,
    privkey,
    fundTxId,
    fundVout,
    localFundPubkey,
    remoteFundPubkey,
    oraclePubkey,
    oracleRValues,
    messagesList: MessagesToMessagesList(messages),
    fundInputAmount,
  };

  return cfddlcjs.CreateCetAdaptorSignatures(req).adaptorPairs;
}
```

So the discrepancy I mentioned above can't be the cause of the issue. Any ideas?

**Comment by satirn** [comment]
I've tried calling the function with the exact data provided in the [CreateCetAdaptorSignatures test](https://github.com/AtomicFinance/cfd-dlc-js/blob/bump-cfd-dlc-to-fix-default-vout-serial-id/wrap_js/__test__/CreateCetAdaptorSignatures.spec.ts) - faced with the same `illegal arguments` error response

**Comment by zpv** [comment]
Resolved.

Issue was related to passing in a WIF rather than a privkey.
